### PR TITLE
Add addfield and addReactions

### PR DESCRIPTION
**Pull request by Juhan280**

### CODE REVIEW

**Comment by DevSpen** [comment]
Before merging, please set `multiple_usages` to false for every command/callback except `onInteraction`.

**Comment by Juhan280** [comment]
> Before merging, please set `multiple_usages` to false for every command/callback except `onInteraction`.

Ok

**Comment by YuzuTheNeko** [comment]
<h1> nice repo <h1>

**Comment by DevSpen** [comment]
> # nice repo

ikr

**Pull request merged**
